spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/asdfgmfc/config-repo
          username: xxx
          password: xxx
          baseDir: C:\Users\Administrator\IdeaProjects\config\basedir
#    bus:
#      trace:
#        enabled: true
  rabbitmq:
    host: 192.168.1.17
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"